export const CONTRACTS = {
    SUPREME_FACTORY: import.meta.env.VITE_SUPREME_FACTORY_ADDRESS || "",
    NFT_ESCROW_TEMPLATE: import.meta.env.VITE_NFT_ESCROW_TEMPLATE || "",
    OTC_ESCROW_TEMPLATE: import.meta.env.VITE_OTC_ESCROW_TEMPLATE || "",
    FREELANCE_ESCROW_TEMPLATE: import.meta.env.VITE_FREELANCE_ESCROW_TEMPLATE || "",
    WETH: import.meta.env.VITE_WETH_ADDRESS || "0x7b79995e5f793A07Bc00c21412e50Ecae098E7f9",
    USDC: import.meta.env.VITE_USDC_ADDRESS || "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238",
} as const;

export const ERC20_ABI = [
    {
        inputs: [{ name: "spender", type: "address" }, { name: "amount", type: "uint256" }],
        name: "approve",
        outputs: [{ name: "", type: "bool" }],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [{ name: "owner", type: "address" }, { name: "spender", type: "address" }],
        name: "allowance",
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ name: "account", type: "address" }],
        name: "balanceOf",
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "decimals",
        outputs: [{ name: "", type: "uint8" }],
        stateMutability: "view",
        type: "function",
    },
] as const;

export const SUPREME_FACTORY_ABI = [
    {
        inputs: [
            { name: "_nftContract", type: "address" },
            { name: "_usdcToken", type: "address" },
            { name: "_pricePerSlot", type: "uint256" },
            { name: "_totalSlots", type: "uint256" },
            { name: "_deadline", type: "uint256" },
            { name: "_allowPartialFill", type: "bool" },
        ],
        name: "createNFTEscrow",
        outputs: [{ name: "", type: "address" }],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            { name: "_tokenOffered", type: "address" },
            { name: "_tokenWanted", type: "address" },
            { name: "_amountOffered", type: "uint256" },
            { name: "_minAmountWanted", type: "uint256" },
            { name: "_maxAmountWanted", type: "uint256" },
            { name: "_deadline", type: "uint256" },
            { name: "_priceOracle", type: "address" },
            { name: "_maxSlippageBPS", type: "uint256" },
        ],
        name: "createOTCEscrow",
        outputs: [{ name: "", type: "address" }],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            { name: "_paymentToken", type: "address" },
            { name: "_contractor", type: "address" },
            { name: "_arbitrator", type: "address" },
            { name: "_milestoneAmounts", type: "uint256[]" },
            { name: "_milestoneDeadlines", type: "uint256[]" },
            { name: "_requiresApproval", type: "bool" },
        ],
        name: "createFreelanceEscrow",
        outputs: [{ name: "", type: "address" }],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "nftEscrowTemplate",
        outputs: [{ name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "otcEscrowTemplate",
        outputs: [{ name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "freelanceEscrowTemplate",
        outputs: [{ name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "platformFeeBPS",
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "feeCollector",
        outputs: [{ name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ name: "", type: "uint256" }],
        name: "deployedEscrows",
        outputs: [{ name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
] as const;

export const NFT_ESCROW_ABI = [
    {
        inputs: [],
        name: "nftOwner",
        outputs: [{ name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "nftContract",
        outputs: [{ name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "usdcToken",
        outputs: [{ name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "pricePerSlot",
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "totalSlots",
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "filledSlots",
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "deadline",
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "state",
        outputs: [{ name: "", type: "uint8" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ name: "numSlots", type: "uint256" }],
        name: "contribute",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "finalize",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "cancel",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "claimRefund",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [{ name: "contributor", type: "address" }],
        name: "contributions",
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
] as const;

export const OTC_ESCROW_ABI = [
    {
        inputs: [],
        name: "maker",
        outputs: [{ name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "tokenOffered",
        outputs: [{ name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "tokenWanted",
        outputs: [{ name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "amountOffered",
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "minAmountWanted",
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "maxAmountWanted",
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "deadline",
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "state",
        outputs: [{ name: "", type: "uint8" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ name: "amount", type: "uint256" }],
        name: "take",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "cancel",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
] as const;

export const FREELANCE_ESCROW_ABI = [
    {
        inputs: [],
        name: "client",
        outputs: [{ name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "contractor",
        outputs: [{ name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "arbitrator",
        outputs: [{ name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "paymentToken",
        outputs: [{ name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "totalAmount",
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "releasedAmount",
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "milestoneCount",
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "state",
        outputs: [{ name: "", type: "uint8" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ name: "index", type: "uint256" }],
        name: "milestones",
        outputs: [
            { name: "amount", type: "uint256" },
            { name: "deadline", type: "uint256" },
            { name: "status", type: "uint8" },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ name: "milestoneIndex", type: "uint256" }],
        name: "releaseMilestone",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [{ name: "milestoneIndex", type: "uint256" }],
        name: "requestRelease",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "raiseDispute",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [{ name: "clientShare", type: "uint256" }, { name: "contractorShare", type: "uint256" }],
        name: "resolveDispute",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
] as const;
